# Generated by Django 5.0.14 on 2026-09-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('prep_time_minutes', models.PositiveIntegerField()),
                ('cost_per_serving', models.DecimalField(decimal_places=2, max_digits=6)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('protein_grams', models.PositiveIntegerField(default=0)),
                ('carbs_grams', models.PositiveIntegerField(default=0)),
                ('fats_grams', models.PositiveIntegerField(default=0)),
                ('macro_framework', models.CharField(blank=True, max_length=100)),
                ('in_cart', models.BooleanField(default=False)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
