# Generated by Django 5.0.14 on 2026-09-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_healthprofile_allergy'),
        ('api', '0002_recipe'),
    ]

    operations = [
    ]
