# Generated by Django 5.0.14 on 2026-10-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
    ]
